sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
- "10.9.0"
branches:
  only:
  - master
  - development

before_install: 
  - npm install npm@latest -g
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install -g ionic cordova
  - npm install -g @angular/cli

before_script:
  - cd client/
  - npm install

script:
  - npm run lint
  - npm run test
  - npm run e2e
  
before_deploy:
  - pwd
  - cd ..
  - pwd
  
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    master: 
      secure: mtcLa73iuwwMxWddtmDec3aNhwsqlr3a83NjqFBLBuadRSdGpnnDw2bjzCspP5Rk8FT0T8ONW6o/puJeviLBMjYMeuESNWK5yML7w9EHIM7d2piqhUI/kNb338pPH/hTfVc3CGLIBcP+nTbIjpWl+Ton8dk5Qt4GugPsPwFJnVFy9BaFYW/Roxx4mUV7WBkS0H1HCEjmlWCCueKtMMQktRjgA7vgfxXYaGGIQl39pZjGWgb5/ludMsu/rCM85nXShCp3tBhcPhtHTy6CKPn4OrvI48HuxiiR9CE5reUeXOp3e01zIAlA0oFqJO6ITOdamxE6iQhjtEVDD1RGf15bLUdI0dp/Tuaymfvz6W7WZdzsTa4ONRwOICuplqeBKiBmTWD9D4eLkhW2c8FrUSmySGtgeyveNzf6M0YX4WD8HSMYxUFMyX5zJqRcO7iqt/qf3UnS+72fDOVdZwDTVTlQuNdTj/NDFXbrwtPgAVKBClMZk2gaD1jMYKFkkjw/FRQbkr2JxG7qu/K8BhPKuIH8m8LJp36+ZOC+8kmoRSxSO6OOkfpN+9g4+yc33Xq1xjwOkd/yVZgjBmWXJtPkM0eou1O1qAcWSWLwnO6GFEhfEnpyzxPtfnawmhf9HGdM/zV+CDd34FJypq2Ggs/QERiBmpFgsouCQZRbAf3OMoq0z7g=
    development:  
      secure: mtcLa73iuwwMxWddtmDec3aNhwsqlr3a83NjqFBLBuadRSdGpnnDw2bjzCspP5Rk8FT0T8ONW6o/puJeviLBMjYMeuESNWK5yML7w9EHIM7d2piqhUI/kNb338pPH/hTfVc3CGLIBcP+nTbIjpWl+Ton8dk5Qt4GugPsPwFJnVFy9BaFYW/Roxx4mUV7WBkS0H1HCEjmlWCCueKtMMQktRjgA7vgfxXYaGGIQl39pZjGWgb5/ludMsu/rCM85nXShCp3tBhcPhtHTy6CKPn4OrvI48HuxiiR9CE5reUeXOp3e01zIAlA0oFqJO6ITOdamxE6iQhjtEVDD1RGf15bLUdI0dp/Tuaymfvz6W7WZdzsTa4ONRwOICuplqeBKiBmTWD9D4eLkhW2c8FrUSmySGtgeyveNzf6M0YX4WD8HSMYxUFMyX5zJqRcO7iqt/qf3UnS+72fDOVdZwDTVTlQuNdTj/NDFXbrwtPgAVKBClMZk2gaD1jMYKFkkjw/FRQbkr2JxG7qu/K8BhPKuIH8m8LJp36+ZOC+8kmoRSxSO6OOkfpN+9g4+yc33Xq1xjwOkd/yVZgjBmWXJtPkM0eou1O1qAcWSWLwnO6GFEhfEnpyzxPtfnawmhf9HGdM/zV+CDd34FJypq2Ggs/QERiBmpFgsouCQZRbAf3OMoq0z7g=  
  app: 
    master: penalty-catalog
    development: penalty-catalog-dev
