sudo: required
dist: trusty
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
language: node_js
node_js:
- 10.9.0
branches:
  only:
  - master
  - development
before_install:
- npm install npm@latest -g
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- npm install -g ionic cordova
- npm install -g @angular/cli
before_script:
- cd client/
- npm install
script:
- npm run lint
- npm run test
- npm run e2e
before_deploy:
- pwd
- cd ..
- pwd
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: OGZOdeTYL8ZFwgD7NFoMpv6w8kMgzgE4B2195irovR1D2OP+qDUbRGsAwcOIU8IGAJi3l+GbV/VqBBWRe4Y7Z+bQKb9lY6yumhOMRVrJXipXTCd9yeJqZuTyH63Um/ZU8Mi41ybCxbnJuEBky7SlYK8joOqHnCSo0lWu3ymBzMRkl1Ncvi3pRJLIrxqkOB73lxXFwlDdHAYaOzr/NOLfEb/RAik4iQ+KZYYbrKeEq4xbEIv2asMn026E2A5CjzXBO7xwGeHKp5mXvkp90zQl7tHrbfUJs2QbnTk1BCK4pSDWblFe5y/nehgcBV+qBuKCPsXD0PJZH3iO89bA9sRwB7lOx2Ml2DwTBLMY8R98Rv/1Xzan2pcQlT3yvR3DLCzGJT8Wvfm96bnNl/g7oJvpooNz/xhi+DPUoKuGdGYC8ZIF+c7KoG+mZHOaBD3jvnWTDy0A2xIo6+Tj+jr8ltPR9/z093gti0fof36p67YfuMf9DSARI7cu0xzB8gdAdZvL6m4sMPj5uCNq9QNjdN1tVAye2FLxtULiI4Sp+jyTP/L/H3nyTUtTk0d4Sx80BEclLbmVbFzvB3/JLiAEzKs2yxAhtbot+p8+Pr21b1em1F6DL5hzbURp32UE1fbppqJw1rg8bIgCMVNT2PI9aRopz5b8Xmv3PZ9VMcTDgDVAhBQ=
  app:
    master: penalty-catalog
    development: penalty-catalog-dev
